#!/bin/bash
set -e

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cp ../bin/purifier-server .
docker build -t ${REPO}/purifier-server:${TAG} .

echo Built ${REPO}/purifier-server:${TAG}
